<a href="https://colab.research.google.com/github/Sruthi5311/Neural/blob/ICP2/700761799_ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Venkata Sruthi Kakumani

700761799

1.Create a class Employee and then do the following:

• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.


In [ ]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Sruthi", "Kakumani", 100000, "Manager")
employee2 = Employee("Babbulu", "Veepuri", 90000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Raju", "Varma", 75000, "Finance")
fulltime_employee2 = FulltimeEmployee("Lohi", "datta", 60000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)
print("Total Employees:", Employee.employee_count)

Average Salary for Employees: 47500.0
Average Salary for Fulltime Employees: 33750.0
Total Employees: 4


2.Numpy

Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)

In [ ]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [ 9.8866437   4.78490025  4.3787388  11.59741913  8.97211398 19.05191196
 14.27345386 12.49422219  7.44831658 12.08723859  9.83075724  2.74889011
 17.57379184  5.15172943 12.86341136  3.56287241  7.13488855  2.11767327
 10.01872626 18.74353392]


In [ ]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)


[[ 9.8866437   4.78490025  4.3787388  11.59741913  8.97211398]
 [19.05191196 14.27345386 12.49422219  7.44831658 12.08723859]
 [ 9.83075724  2.74889011 17.57379184  5.15172943 12.86341136]
 [ 3.56287241  7.13488855  2.11767327 10.01872626 18.74353392]]


In [ ]:
# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 9.8866437   4.78490025  4.3787388   0.          8.97211398]
 [ 0.         14.27345386 12.49422219  7.44831658 12.08723859]
 [ 9.83075724  2.74889011  0.          5.15172943 12.86341136]
 [ 3.56287241  7.13488855  2.11767327 10.01872626  0.        ]]
